containerized dag deployment code
santoshgopane/FugetronTraining pull request #2
Opened 2023-11-28 12:51 UTC by abhisheksawalkar2001

2023-11-28 18:00 UTC, santoshgopane commented on src/Dockerfile
> +
add upgrade pip piece here

2023-11-28 18:01 UTC, santoshgopane commented on src/app/common/config.py
> +import os
either segregate them by class or functions

2023-11-28 18:06 UTC, santoshgopane commented on src/app/main.py
> +        conn = http.client.HTTPSConnection(host=config.api_host)
use requests module of python for such tasks

2023-11-28 18:08 UTC, santoshgopane commented on src/app/main.py
> +        def prep(row):
You should not use methods to tackle, this looks like to handle a single case. But you should think of solution that is applying to all data.

2023-11-28 18:08 UTC, santoshgopane commented on src/app/main.py
> +        engine = create_engine(
add into config.py

2023-11-28 18:09 UTC, santoshgopane commented on src/app/main.py
> +if __name__ == "__main__":
dont have this here instead create another python file that creates class object

2023-11-28 18:09 UTC, santoshgopane commented on src/requirements.txt
> +pandas
have specific version of each package.

2023-11-28 18:09 UTC, santoshgopane requested changes
Please work on the changes and resubmit

2023-11-29 09:29 UTC, abhisheksawalkar2001 commented on src/app/common/config.py
> +import os
means all cred in classes and functions bind

2023-11-29 13:04 UTC, santoshgopane commented on src/app/common/config.py
> +import os
yes

2023-11-29 14:21 UTC, abhisheksawalkar2001 commented on src/app/main.py
> +if __name__ == "__main__":
can i remove this line and direct create a class object and call functions

2023-11-30 18:16 UTC, merged